# Generated by Django 2.2.7 on 2024-03-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applicationdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Application_id', models.CharField(max_length=50)),
                ('Application_type', models.CharField(max_length=255)),
                ('Aadhar_no', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=255)),
                ('Details', models.CharField(max_length=255)),
                ('Date', models.CharField(max_length=50)),
                ('Time', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='certificatedetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Request_id', models.CharField(max_length=50)),
                ('Certificate_no', models.CharField(max_length=255)),
                ('Type', models.CharField(max_length=255)),
                ('Issue_Date', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=255)),
                ('Father_Name', models.CharField(max_length=255)),
                ('Mother_Name', models.CharField(max_length=255)),
                ('Reason', models.CharField(max_length=1000)),
                ('Date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='certificaterequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Request_id', models.CharField(max_length=50)),
                ('Scheme_id', models.CharField(max_length=50)),
                ('Aadhar_no', models.CharField(max_length=50)),
                ('Apply_date', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='citizendetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aadhar_no', models.CharField(max_length=50)),
                ('First_name', models.CharField(max_length=255)),
                ('Last_name', models.CharField(max_length=255)),
                ('Father_name', models.CharField(max_length=255)),
                ('Mother_name', models.CharField(max_length=255)),
                ('DateOfBirth', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=10)),
                ('Mobile_no', models.CharField(max_length=15)),
                ('Cast', models.CharField(max_length=255)),
                ('Sub_Cast', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaints_id', models.CharField(max_length=50)),
                ('Givenby', models.CharField(max_length=255)),
                ('Complaints_On', models.CharField(max_length=255)),
                ('Date', models.CharField(max_length=50)),
                ('Time', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email_id', models.CharField(max_length=50)),
                ('Message', models.CharField(max_length=500)),
                ('Feedback', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='schemes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Schemes_id', models.CharField(max_length=50)),
                ('Schemes_name', models.CharField(max_length=255)),
                ('Details', models.CharField(max_length=500)),
                ('Release_Details', models.CharField(max_length=255)),
                ('Start_Date', models.CharField(max_length=20)),
                ('Eligibility', models.CharField(max_length=255)),
                ('Releasedby', models.CharField(max_length=255)),
                ('Min_age', models.CharField(max_length=50)),
                ('Max_age', models.CharField(max_length=50)),
                ('Mobile_no', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='userlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=20)),
                ('utype', models.CharField(max_length=20)),
            ],
        ),
    ]
